eureka:
    client: 
        register-with-eureka: true
        fetch-register: true
        defaultZone: http://localhost:8761/eureka

management:
    endpoint:
        web:
            exposure: 
                include: "*"
        health:
            show-details: always
            circuitbreakers:
                enabled: true
            ratelimiters:
                enabled: true
spring:
    cloud:
        loadbalancer:
            ribbon:
                enabled: false
        gateway:
            routes:
                - id: player
                  uri: lb://player-service/player
                  predicates:
                    - Path=/player/**
                  filters:
                    - name: CircuitBreaker
                    args:
                      name: player-service
                      sliding-window-size: 20
                      permitted-number-of-calls-in-half-open-state: 5
                      failure-rate-threshold: 50
                      wait-duration-in-open-state: 15s
                - id: game
                  uri: lb://game-service/play
                  predicates:
                    - Path=/play/**
                - id: canvas
                  uri: lb://canvas-service/canvas
                  predicates:
                    - Path=/canvas/**